Update swift-docc.yml

diff --git a/.github/workflows/swift-docc.yml b/.github/workflows/swift-docc.yml
--- a/.github/workflows/swift-docc.yml
+++ b/.github/workflows/swift-docc.yml
@@ -2,8 +2,7 @@ name: Generate Documentation
 
 on:
   workflow_run:
-    workflows:
-      - Swift Build & Test
+    workflows: [Swift Build & Test]
     types:
       - completed
 
@@ -19,11 +18,11 @@ jobs:
     container:
       image: swiftlang/swift:nightly-5.6-focal
     steps:
-      - name: Make fail if the previous workflow was failed
-        if: ${{ github.event.workflow_run.conclusion != 'success' }}
-        run: |
-          echo '::error::Previous workflow was failed'
-          exit 1
+      # - name: Make fail if the previous workflow was failed
+      #   if: ${{ github.event.workflow_run.conclusion != 'success' }}
+      #   run: |
+      #     echo '::error::Previous workflow was failed'
+      #     exit 1
       - name: Show Swift version
         run: swift --version
       - uses: actions/checkout@v2
